name: physionet2020
channels:
- fastai
- pytorch
- defaults
dependencies:
- jupyter
- pytorch>=1.3.0
- torchvision
- matplotlib
- fastprogress
- pillow=6.1
- python>=3.7
- pip
- scikit-learn
- scipy
- pip:
  - nbdev
  - fastai2
  - fastcore
  - wget
  - scikit-image
  - opencv-python
  - ecg_plot
