# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"data_path": "01_preprocess.ipynb",
         "data_path_trn": "01_preprocess.ipynb",
         "proc_path": "01_preprocess.ipynb",
         "trn_path": "01_preprocess.ipynb",
         "meta_path": "01_preprocess.ipynb",
         "trn_path.mkdir(exist_ok": "01_preprocess.ipynb",
         "meta_path.mkdir(exist_ok": "01_preprocess.ipynb",
         "meta_trn_pth": "01_preprocess.ipynb",
         "cols": "01_preprocess.ipynb",
         "pad_batch": "02_train.ipynb",
         "OpenEEG": "02_train.ipynb"}

modules = ["preprocess.py",
           "train.py"]

doc_url = "https://bearpelican.github.io/physionet2020/"

git_url = "https://github.com/bearpelican/physionet2020/tree/master/"

def custom_doc_links(name): return None
