# AUTOGENERATED! DO NOT EDIT! File to edit: 01_preprocess.ipynb (unless otherwise specified).

__all__ = ['data_path', 'data_path_trn', 'proc_path', 'trn_path', 'meta_path', 'meta_trn_pth', 'cols']

# Cell
from fastai2.basics import *
from nbdev.export import *
import re

# Cell
data_path = Path('/mnt/data1/wamri/physionet2020')
data_path_trn = data_path/'Training_WFDB'


proc_path = data_path/'processed'
trn_path = proc_path/'trn'
meta_path = proc_path/'meta'
trn_path.mkdir(exist_ok=True)
meta_path.mkdir(exist_ok=True)

meta_trn_pth = meta_path/'df_trn.csv'

# Cell
cols = ['Normal','AF','I-AVB','LBBB','RBBB','PAC','PVC','STD','STE']